
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tfhnvirervrtciakjaek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmaG52aXJlcnZydGNpYWtqYWVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1MDAyMjMsImV4cCI6MjA1ODA3NjIyM30.5lIhkTxGYJ6DNVwpZmia7KICgLapnC5a8FjHhtMLFkw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true
  }
});
